config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  get 'feed/show'
  get 'users/new'
  get 'users/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "feed#show"
   
  get "sign_up", to: "users#new"

  post "sign_up", to: "users#create"

  get "login", to: "sessions#new"

  post "login", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  resource :profile, only: [:show, :update], controller: "users"

  resources :listings, except: :index do
    scope module: :listings do
      post :draft, to: "drafts#create", on: :collection
      patch :draft, to: "drafts#update"
      member do # both asr similar using member is expicit
        get :renew, to: "renew#show"
      end
      resource :contact, only: [:show], controller: "contact"
    end
    resource :saved_listings, only: [:create, :destroy], path: "save"
  end
  
  # only for cosmetic reeasons
  resource :saved_listings, only: :show

  resource :my_listings, only: :show

  namespace :users do
    patch "change_password", to: "passwords#update"
    resources :password_resets, only: [:new, :create, :update, :edit]
    resources :activation, only: [:show]
  end

  resource :search, only: :show, controller: "feed/searches"

  resource :search, only: :show, controller: "feed/searches" do
    get "tags/:tag", to: "feed/searches/tags#show", as: "tags"
  end


  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create, :index]
    get :unread_badge, to: "conversations/unread_badge#show", on: :collection
  end

  mount Sidekiq::Web => '/sidekiq'

end

# Draft Routes:

#     POST /listings/draft -> Listings::DraftsController#create
#     PATCH /listings/:id/draft -> Listings::DraftsController#update

# Saved Listings Routes:

#     POST /listings/:listing_id/save -> SavedListingsController#create
#     DELETE /listings/:listing_id/save -> SavedListingsController#destroy

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id              :bigint           not null, primary key
#  condition       :enum
#  price           :integer
#  published_on    :datetime
#  searchable      :tsvector
#  status          :enum             default("published")
#  tags            :string           is an Array
#  title           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  creator_id      :bigint
#  organization_id :bigint           not null
#
# Indexes
#
#  index_listings_on_creator_id       (creator_id)
#  index_listings_on_organization_id  (organization_id)
#  index_listings_on_searchable       (searchable) USING gin
#  index_listings_on_tags             (tags) USING gin
#
# Foreign Keys
#
#  fk_rails_...  (creator_id => users.id)
#  fk_rails_...  (organization_id => organizations.id)
#
class Listing < ApplicationRecord
  belongs_to :creator, class_name: "User"
  belongs_to :organization

  include HasAddress, PermittedAttributes, AccessPolicy, Publishable, 
          Expireable, Renewable, Searchable

  has_one_attached :cover_photo
  has_rich_text :description
  has_many :conversations


  enum condition: {
    mint: "mint", near_mint: "near_mint", used: "used", defective: "defective"
  }

  enum status: {
    draft: "draft", published: "published", expired: "expired"
  }

  validates :title, length: { in: 10..100 }
  validates :price, numericality: { only_integer: true }
  validates :tags, length: { in: 1..5 }
  validates :cover_photo, presence: true
  validates :description, presence: true


  before_save :downcase_tags

  scope :feed, -> { published.order(created_at: :desc).includes(:address) }

  def saved?
    return false unless Current.user.present?

    Current.user.saved_listings.exists?(id: self.id)
  end

  def expiry_date
    published_on.end_of_day + 30.days
  end

  private 

    def downcase_tags
      self.tags = tags.map(&:downcase)
    end

end

app/models/listing/access_policy.rb
module Listing::AccessPolicy
  def show?
    true
  end
  

  def edit?
    organization == Current.organization
  end

  def update?
    organization == Current.organization
  end

  def destroy?
    organization == Current.organization
  end

  def can_save?
    organization != Current.organization
  end

  def can_contact?
    organization != Current.organization
  end

end

app/models/listing/expireable.rb
module Listing::Expireable
  extend ActiveSupport::Concern

  included do
     after_save_commit :queue_expire_job, 
     if: -> {
      (id_previously_was.nil? && published?) || 
      (status_previous_change in [_, "published"])
     }
  end

  def expiry_date
    published_on.end_of_day + 30.days
  end

  private

  def queue_expire_job
    Listings::ExpireJob
    .set(wait_until: expiry_date)
    .perform_later(self)
  end


end

app/models/listing/permitted_attributes.rb
module Listing::PermittedAttributes
  extend ActiveSupport::Concern

  class_methods do
    def permitted_attributes
      [:title, :price, :condition, :cover_photo, :description ,tags: [], address_attributes: Address.permitted_attributes]
    end

  end

end

app/models/listing/publishable.rb
module Listing::Publishable
   extend ActiveSupport::Concern

   included do 
      before_create :set_published_date, if: :published?
      before_save :set_published_date, if: -> { status_change_to_be_saved in [_, "published"]}
   end

   def set_published_date
     self.published_on = Time.zone.now
   end
end

app/models/listing/renewable.rb
module Listing::Renewable
   extend ActiveSupport::Concern

   included do
     after_save_commit :queue_renewed_job,
      if: -> {
        (id_previously_was.nil? && published? ) ||
        (status_previous_change in [_, "published"])
      }
   end

   def renew_date
     expiry_date.beginning_of_day  - 1.day
   end

   def renew_date_past?
    (expiry_date - 1.hours).past?
   end

   def send_renew_mail
    token = self.creator.generate_token_for(:authenticate)
    puts "Renew mail sent"   
    UserMailer.with(user: self.creator)
              .renew(token, id)
              .deliver_later

   end

   private 

   def queue_renewed_job
      Listings::RenewJob.set(wait_until: renew_date).perform_later(self)
   end
end

app/models/listing/searchable.rb
module Listing::Searchable
  extend ActiveSupport::Concern
  
  included do
    scope :search, ->(query) {
    websearch_to_tsquery = Arel::Nodes::NamedFunction.new(
    "websearch_to_tsquery",
    [
    Arel::Nodes::SqlLiteral.new("'english'"),
    Arel::Nodes::SqlLiteral.new(
    sanitize_sql_array(["?", query])
    )
    ]
    )
    ts_rank = Arel::Nodes::NamedFunction.new(
    "ts_rank",
    [arel_table[:searchable], websearch_to_tsquery]
    )
    where = Arel::Nodes::InfixOperation.new(
    "@@",
    arel_table[:searchable],
    websearch_to_tsquery
    )
    select(Arel.star, ts_rank.as("rank"))
    .where(where)
    .order("rank DESC")
    }


    scope :near, ->(location) {
      select(Arel.star).joins(:address).merge(Address.near(location))
    }

    scope :filter_by_tags, ->(tags) {
      where("tags @> ARRAY[?]::varchar[]", tags)
    }
    end


end

app/models/listings/search.rb
class Listings::Search 
  include ActiveModel::Model

  attr_accessor :query, :location, :tags


  def initialize(attributes={})
     super
     Rails.logger.info "Tags : ---- #{self.tags}" 
     self.query = nil unless query.present?
     self.location = nil unless location.present?
     self.tags = nil unless tags&.compact_blank.present?
  end

  # def perform
  #   if location.present?
  #      Listing.feed.search(query).near(location)
  #   else
  #      Listing.feed.search(query)
  #   end
  # end
  # 
  def perform
     case [query, location, tags]
     in [String, nil, nil]
        Listing.feed.search(query)
     in [String, String, nil]
        Listing.feed.search(query).near(location)
     in [nil, nil, Array]
        Listing.feed.filter_by_tags(tags)   
     in [String, nil, Array]
         Listing.feed.search(query).filter_by_tags(tags)           
     else
      raise "Error in search data"  
     end
  end
end

app/controllers/listings/contact_controller.rb
class Listings::ContactController < ApplicationController
   before_action :load_listing
   before_action -> { authorize! @listing.can_contact? }
  
  def show
    @conversation = @listing.conversations.find_or_create_by(
      buyer: Current.organization
      )
    @message = @conversation.messages.build  
    @pagy, @messages = pagy(@conversation.messages, items: 5) 


    # @conversation.messages.build is designed specifically for associations and automatically handles the association between the new message and @conversation. 
    # It adds the new message to the messages collection of @conversation.
  end


  private

    def load_listing
      @listing = Listing.find(params[:listing_id])
    end

end

app/controllers/listings/drafts_controller.rb
class Listings::DraftsController < ApplicationController

  skip_authorization only: :create

  def create
    @listing = Listing.new(listing_params.with_defaults(
      creator: Current.user,
      organization: Current.organization,
      status: :draft
    ))
    if(@listing.save)
      redirect_to listing_path(@listing), flash: { success: t(".success")}, status: :see_other
    else
      render "listings/new", status: :unprocessable_content
    end


  end

  def update
    @listing.assign_attributes( listing_params.with_defaults(
      status: :draft
    ))
    if @listing.save
      redirect_to listing_path(@listing), status: :see_other, flash: { success: t(".success")}
    else
      render "listings/edit", status: :unprocessable_entity
    end
  end


  private

  def listing_params
    params.require(:listing).permit(Listing.permitted_attributes)
  end

  def authorizable_resource
    @listing = Listing.find(params[:listing_id])
  end
end

app/controllers/listings/renew_controller.rb
class Listings::RenewController < ApplicationController

  skip_authorization only: :show

  skip_authentication only: :show


  before_action :load_user, :load_listing

  def show
    @listing.published_on = Time.now unless @listing.renew_date_past?
    if(@listing.save)
      puts "saving publised on"
      redirect_to listing_path(@listing), flash: { success: t(".success")}, status: :see_other
    else
      render "listings/new", status: :unprocessable_content
    end
  end

  private 

  def load_listing
    @listing = Listing.find(params[:id])
  end

  def load_user
    @user = Current.user || User.find_by_token_for(:authenticate, params[:token])
   
    redirect_to root_path,
      status: :see_other,
      flash: {
      error: t("listings.renew.invalid_link")
    } unless @user.present?
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  # before_action :load_listing, except: [:new, :create]
  allow_unauthenticated only: :show
  skip_authorization only: [:new, :create]

  drop_breadcrumb -> { @listing.title },-> { listing_path(@listing) },except: [:new, :create]

  def new
    drop_breadcrumb t("listings.breadcrumbs.new")
    @listing = Listing.new
    @listing.build_address
  end

  def create
    drop_breadcrumb t("listings.breadcrumbs.new")
    @listing = Listing.new(listing_params.with_defaults(creator: Current.user, 
        organization: Current.organization,
        status: :published))
    if @listing.save
      redirect_to listing_path(@listing), flash: { success: t(".success")}, status: :see_other
    else
      render :new, status: :unprocessable_content  
    end
  end

  def show
  end

  def edit
    drop_breadcrumb t("listings.breadcrumbs.edit")
  end

  def update
    drop_breadcrumb t("listings.breadcrumbs.edit")
    @listing.assign_attributes(
         listing_params.with_defaults(
           status: :published
         )
      )
    if @listing.save
      flash[:success] = t(".success")
      recede_or_redirect_to listing_path(@listing), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @listing.destroy 
    flash[:success] = t(".success")
    redirect_to my_listings_path, status: :see_other
  end

  private 

  # def listing_params
  #   params.require(:listing).permit(Listing.permitted_attributes)
  # end

  def authorizable_resource
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.fetch(:listing, {}).permit(
      Listing.permitted_attributes
    )
  end


end

app/helpers/listings/contact_helper.rb
module Listings::ContactHelper
end

app/helpers/listings/drafts_helper.rb
module Listings::DraftsHelper
end

app/helpers/listings/renew_helper.rb
module Listings::RenewHelper
end

app/helpers/listings_helper.rb
module ListingsHelper

  def listing_status_tag_classes(listing)
    classes = ["tag"]
    classes = ["tag"]
    classes << "is-danger" if listing.expired?

    classes.join(" ")
  end
end

app/views/listings/_form.html.erb
<%# locals: (form:) -%>
<div class="block">
<%= form.label :title, class: "label" %>
<%= form.text_field :title, class: "input is-large" %>
</div>
<%= render "application/image_field",form: form, attribute: :cover_photo,
label: t(".cover_photo") %>
<layout-columns class="columns is-centered">
    <layout-column class="box column is-half mt-6 p-5 m-4">
    <div class="is-flex is-flex-direction-column">
    <form-field class="field">
      <%= form.label :price, class: "label" %>
    <form-field class="field has-addons">
        <p class="control">
          <a class="button is-static">
            £
          </a>
      </p>
    <p class="control is-expanded">
        <%= form.text_field :price, inputmode: :numeric, class: "input" %>
     </p>
      </form-field>
    </form-field>
    <form-field class="field">
       <%= form.label :condition, class: "label" %>
       <div class="select is-fullwidth">
       <%= form.select :condition,
       Listing.human_enum_options(:condition) %>
     </div>
    </form-field>
    <form-field class="field">
       <%= render "listings/tags_field", form: form %>
    </form-field>
    <form-field class="field">
        <%= form.label :address, class: "label is-large" %>
      <div class="box">
         <%= render "addresses/fields", form: form %>
      </div>
    </form-field>
    </div>
    </layout-column>
      <layout-column class="box column is-half mt-6 p-5 m-4">
        <form-field class="field">
          <%= form.label :description, class: "label" %>
          <%= form.rich_text_area :description %>
          <%# no need the below error rendering its already coming %>
          <%# <%= tag.p class: "help is-danger" do %>
          <%# <%= form.object.errors %>
          <%# # .messages_for(:description).to_sentence %> 
          <%# <% end if form.object.errors.include?(:description) %> 
       </form-field>
    </layout-column>
</layout-columns>

app/views/listings/_listing.html.erb
<%# locals: (listing:) -%>

<% turbo_refreshes_with method: :morph, scroll: :preserve %>


<div class="card">
  <div class="card-image">
    <%= save_button(listing) %>
    <%= link_to listing_path(listing) do %>
    <figure class="image is-4by3">
      <% if listing.cover_photo.present? %>
        <%= image_tag listing.cover_photo.variant(resize_to_fit: [500, 500]), loading: :lazy %>
      <% end %>
    </figure>
    <% end %>
  </div>
    <div class="card-content is-block">
        <article class="content">
            <%= link_to listing_path(listing) do %>
              <h1 class="title mb-2">
            <%= listing.title %>
              </h1>
            <% end %>
            <%= render "listings/status", listing: listing %>
            <%= render "listings/tags", listing: listing %>
              <dl class="block">
              <dd class="has-text-weight-semibold is-size-5 m-0">
            £<%= listing.price %>
              </dd>
              <dd class="tag is-link has-text-weight-semibold m-0">
            <%= listing.human_enum_value(:condition) %>
              </dd>
              <dd class="has-text-weight-medium m-0 mt-4">
              <span class="icon-text is-align-items-center">
            <%= svg("location", class: "icon is-small mr-2", fill: "#444"
            ) %>
            <span>
              <%= listing.address.redacted %>
              <%= render "listings/save_button", listing: listing %>
                </span>
              </span>
             </dd>
            </dl>
        </article>
    </div>
</div>

app/views/listings/_save_button.html.erb
<% if logged_in? %>

  <% if listing.saved? %>
      <%= button_to listing_saved_listings_path(listing),
      class: "button is-secondary is-medium",
      method: :delete do %>
        <%= svg "heart", class: "icon is-small mr-3", fill: "#f00" %>
        <span><%= t(".unsave") %></span>
      <% end %>
  <% else %>
      <%= button_to listing_saved_listings_path(listing), class: "button is-secondary is-medium" do %>
        <%= svg "heart", class: "icon is-small mr-3" %>
        <span><%= t(".save") %></span>
      <% end %>
  <% end %>

<% end %>

app/views/listings/_status.html.erb
<%# locals: (listing:)  -%>

<%= tag.div class: "field block" do %>
    <%= tag.span class: listing_status_tag_classes(listing) do %>
        <strong>
        <%= listing.human_enum_value(:status) %>
        </strong>
    <% end %>
<% end unless listing.published? %>

app/views/listings/_tag.html.erb
<%# locals: (form: nil, value:) -%>

<ui-tag class="control tags has-addons" data-controller="remove-element">
    <%= tag.span class: "tag is-primary" do %>
      #<%= value %>
    <% end %>

    <% if form.present? %>
      <%= form.fields_for(:tags) do |fields| %>
        <%=fields.hidden_field nil, id: nil, value: value%>
      <% end %>
     <%= tag.a class: "tag is-primary is-delete",
       data: { action: "remove-element#remove" } %> 
       <% else %>
      <%= link_to tags_search_path(CGI.escape(value)) do %>
      <%= tag.span class: "tag is-primary" do %>
         #<%= value %>
      <% end %>
      <% end %>
    <% end %>
</ui-tag>

app/views/listings/_tags.html.erb
<%# locals: (listing:) -%>
<%= tag.layout_container(class: "field is-grouped is-grouped-multiline",
) do %>
    <% listing.tags.each do |value| %>
      <%= render "listings/tag", value: value %>
    <% end %>
<% end %>

app/views/listings/_tags_field.html.erb
<form-field class="field" data-controller="tags">
    <%= form.label :tags, class: "label" %>
    <p class="has-text-weight-medium has-text-grey is-italic mb-2">
    <%= t(".description") %>
    </p>
    <%= tag.layout_container class: "field is-grouped is-grouped-multiline",
    data: {
       tags_target: "container"
    } do %>
     <% form.object.tags.each do |value| %>
        <%= render "listings/tag", value: value, form: form%>
     <% end if form.object.tags.present?%>
    <% end %>
<form-field class="field is-grouped">
    <div class="control is-expanded">
    <%= text_field_tag nil, nil,
    class: "input", data: { tags_target: "input"} %>
    </div>
    <div class="control">
        <button class="button is-info" type="button" data-action="tags#addTag">
        <%= t(".add_tag") %>
        </button>
    </div>
  </form-field>
  <%= tag.p class: "help is-danger" do %>
   <%= form.object.errors.messages_for(:tags).to_sentence %>
  <% end if form.object.errors.include?(:tags) %>
  <template data-tags-target = "template">
    <%= render "listings/tag", value: "{value}", form: form %>
</template>
</form-field>

app/views/listings/edit.html.erb
<%= content_for(:title) do %>
  <%= @listing.title %>
<% end %>
<layout-columns class="columns is-centered">
<%= form_with(model: @listing, class: "column is-10", id: "edit_listing_form"
) do |form| %>
   <%= render "listings/form", form: form %>
<% end %>
</layout-columns>
<layout-columns class="columns is-centered">
    <layout-column class="column is-10">
        <layout-group class="buttons is-right">
        <%= button_to t(".delete"), listing_path(@listing), method: :delete, form: {data: { turbo_confirm: t(".confirm_delete")}}, class: "button is-danger is-medium m-3" %>
        <% if @listing.draft? %>
          <%= submit_tag t(".update"),
           form: "edit_listing_form",
           formactiion: listing_draft_path(@listing),
           class: "button is-secondary is-medium m-3" %>
          <% end %>
        <%= submit_tag t(".publish"),form: "edit_listing_form", class: "button is-primary is-medium m-3" %>
        </layout-group>
    </layout-column>
</layout-columns>

app/views/listings/new.html.erb
<layout-columns class="columns is-centered">
<%= form_with( model: @listing, class: "column is-10", id: "new_listing_form" ) do |form| %>
  <%= render "listings/form", form: form %>
<% end %>
</layout-columns>

<layout-columns class="columns is-centered">
  <layout-column class="column is-10">
    <layout-group class="buttons is-right">
       <%= submit_tag t(".save_as_draft"), form: "new_listing_form", formaction: draft_listings_path, 
       formmethod: :post, class: "button is-secondary is-medium m-3"%>
       <%= submit_tag t(".publish"), form: "new_listing_form", class: "button is-primary is-medium m-3" %>
    </layout-group>
  </layout-column>
</layout-columns>

app/views/listings/show.html.erb
<%= content_for(:title) do %>
  <%= @listing.title %>
<% end %>

<% turbo_refreshes_with method: :morph, scroll: :preserve %>

<%= turbo_stream_from Current.user, channel: "SaveListingsChannel" %>
<div id="listing_<%= @listing.id %>">
<layout-columns class="columns is-centered">
    <layout-column class="column is-10">
        <div class="mb-3">
            <h1 class="title is-inline">
               <%= @listing.title %>    <%= save_button(@listing) %>
            </h1>
            <% if @listing.edit? %>
              <%= link_to t(".edit"), edit_listing_path(@listing) %>
            <% end %>
        </div>
        <layout-columns class="columns is-centered">
            <layout-column class="box column is-half mt-6 p-5 m-4">
                <dl>
                <dt class="has-text-grey">
                <%= t(".posted_by") %>
                </dt>
                <dd class="has-text-weight-semibold is-size-5">
                <%= @listing.creator.name %>
                </dd>
                </dl>
                <dt class="has-text-grey">
                <%= t(".location") %>
                </dt>
                    <dd class="has-text-weight-semibold is-size-5">
                        <%= @listing.address.redacted %>
                    </dd>
                </dl>
                <layout-group class="buttons mt-6">
                    <%= render "listings/save_button", listing: @listing if @listing.can_save? %>
                    <%= link_to listing_contact_path(@listing),
                       class: "button is-primary is-medium", data: { turbo_frame: :modal } do %>
                    <%= svg("message",class: "icon is-small mr-3", fill: "#fff") %>
                    <%= t(".contact") %>
                    <% end if @listing.can_contact?%>
                </layout-group>
            </layout-column>
            <layout-column class="box column is-half mt-6 p-5 m-4">
                <dl>
                    <dt class="has-text-grey">
                        <%= Listing.human_attribute_name(:price) %>
                    </dt>
                    <dd class="has-text-weight-semibold is-size-5">
                        <%= "£#{@listing.price}" %>
                    </dd>
                   <br>
                    <dt class="has-text-grey">
                    <%= Listing.human_attribute_name(:condition) %> 
                    </dt>
                    <dd class="has-text-weight-semibold is-size-5">
                    <%= @listing.human_enum_value(:condition) %>
                    </dd>

                    <br>
                    <dt class="has-text-grey">
                       <%= Listing.human_attribute_name(:description) %>
                    </dt>
                    <dd class="mt-3">
                       <%= @listing.description %>
                    </dd>
                </dl>
            </layout-column>
        </layout-columns>
        <%= render "status", listing: @listing %>
        <%= render "tags", listing: @listing %>
        <div class="has-text-centered">
          <%= link_to url_for(@listing.cover_photo) do %>
          <figure class="image is-inline-block">
          <%= image_tag @listing.cover_photo.variant(resize_to_limit: [800, 800]
            ) %>
         </figure>
       <% end %>
</div>
    </layout-column>
</layout-columns>