config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  get 'feed/show'
  get 'users/new'
  get 'users/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "feed#show"
   
  get "sign_up", to: "users#new"

  post "sign_up", to: "users#create"

  get "login", to: "sessions#new"

  post "login", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  resource :profile, only: [:show, :update], controller: "users"

  resources :listings, except: :index do
    scope module: :listings do
      post :draft, to: "drafts#create", on: :collection
      patch :draft, to: "drafts#update"
      member do # both asr similar using member is expicit
        get :renew, to: "renew#show"
      end
      resource :contact, only: [:show], controller: "contact"
    end
    resource :saved_listings, only: [:create, :destroy], path: "save"
  end
  
  # only for cosmetic reeasons
  resource :saved_listings, only: :show

  resource :my_listings, only: :show

  namespace :users do
    patch "change_password", to: "passwords#update"
    resources :password_resets, only: [:new, :create, :update, :edit]
    resources :activation, only: [:show]
  end

  resource :search, only: :show, controller: "feed/searches"

  resource :search, only: :show, controller: "feed/searches" do
    get "tags/:tag", to: "feed/searches/tags#show", as: "tags"
  end


  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create, :index]
    get :unread_badge, to: "conversations/unread_badge#show", on: :collection
  end

  mount Sidekiq::Web => '/sidekiq'

end

# Draft Routes:

#     POST /listings/draft -> Listings::DraftsController#create
#     PATCH /listings/:id/draft -> Listings::DraftsController#update

# Saved Listings Routes:

#     POST /listings/:listing_id/save -> SavedListingsController#create
#     DELETE /listings/:listing_id/save -> SavedListingsController#destroy

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  buyer_id   :bigint
#  listing_id :bigint
#  seller_id  :bigint
#
# Indexes
#
#  index_conversations_on_buyer_id                               (buyer_id)
#  index_conversations_on_listing_id                             (listing_id)
#  index_conversations_on_seller_id                              (seller_id)
#  index_conversations_on_seller_id_and_buyer_id_and_listing_id  (seller_id,buyer_id,listing_id) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (buyer_id => organizations.id)
#  fk_rails_...  (listing_id => listings.id) ON DELETE => cascade
#  fk_rails_...  (seller_id => organizations.id)
#
class Conversation < ApplicationRecord

  include AccessPolicy, Notifier

  before_validation :set_seller, unless: :persisted?
  
  belongs_to :listing
  belongs_to :seller, class_name: "Organization"
  belongs_to :buyer, class_name: "Organization"

  has_many :messages, dependent: :destroy

  scope :current_organization, -> {
    where(seller: Current.organization).or(where(buyer: Current.organization))
  }

  scope :for_display, -> {
    joins(:messages)
    .includes(:seller, :listing)
    .order(created_at: :desc)
    .distinct
  }


  private
  
  def set_seller
    self.seller = listing.organization
  end

end

app/models/conversation/access_policy.rb
module Conversation::AccessPolicy
  
  def show?(organization = Current.organization)
    organization == seller || organization == buyer
  end

  def can_message?
    show?
  end
  
end

app/models/conversation/notifier.rb
module Conversation::Notifier
  extend ActiveSupport::Concern

  included do
    has_many :notifications, class_name: 'Conversations::Notification',
     dependent: :destroy

    kredis_set :online_participants, typed: :integer
  end

  def notify_recipient(message)
    recipient_id = [seller_id, buyer_id].difference([message.from_id]).first
    unless online_participants.include?(recipient_id)
      notifications.create(
        message: message,
        recipient_id: recipient_id
      )
    end
  end

  def read!
    notifications.unread.update_all(read_at: Time.zone.now)
  end

end

app/models/conversations.rb
module Conversations
  def self.table_name_prefix
    "conversations_"
  end
end

app/models/conversations/notification.rb
# == Schema Information
#
# Table name: conversations_notifications
#
#  id              :bigint           not null, primary key
#  read_at         :datetime
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  conversation_id :bigint
#  message_id      :bigint
#  recipient_id    :bigint
#
# Indexes
#
#  index_conversations_notifications_on_conversation_id  (conversation_id)
#  index_conversations_notifications_on_message_id       (message_id)
#  index_conversations_notifications_on_recipient_id     (recipient_id)
#
# Foreign Keys
#
#  fk_rails_...  (conversation_id => conversations.id) ON DELETE => cascade
#  fk_rails_...  (message_id => messages.id) ON DELETE => cascade
#  fk_rails_...  (recipient_id => organizations.id) ON DELETE => cascade
#
class Conversations::Notification < ApplicationRecord
  include Readable
  
  belongs_to :message
  belongs_to :recipient, class_name: 'Organization'
  belongs_to :conversation

  after_create_commit :deliver_by_email


  private
    def deliver_by_email
      to = recipient.members.first

      ConversationMailer.new_message(
        message,
        to: to,
        reply_to: message.response_email(recipient)
      ).deliver_later
    end

end

app/models/conversations/notification/readable.rb
module Conversations::Notification::Readable
  extend ActiveSupport::Concern
    included do
      scope :unread, -> { where(read_at: nil) }
    end
    def read?
      read_at.present?
    end
    def unread?
      read_at.nil?
    end
    def read!
      update(read_at: Time.zone.now)
    end
end

app/controllers/conversations/unread_badge_controller.rb
class Conversations::UnreadBadgeController < ApplicationController

  layout false

  def show

    @unread_count = Conversations::Notification
    .where(recipient: Current.organization).unread.count

    head :no_content unless @unread_count > 0
    
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  skip_authorization only: :index
  def index
    @conversations = Conversation.current_organization.for_display
  end


  def show 
    @conversation.read!
    @message = @conversation.messages.build
    @pagy, @messages = pagy(@conversation.messages, items: 5) 
  end
  
  private
  
    def authorizable_resource
      @conversation = Conversation.find(params[:id])
    end

end

app/helpers/conversations/unread_badge_helper.rb
module Conversations::UnreadBadgeHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<%# locals: (conversation:) -%>
<%= link_to conversation_path(conversation),
class: "m-2",
data: { turbo_frame: :conversation } do %>
<%= tag.div class: class_names("box",
{ "has-background-info-dark has-text-white":
conversation.seller == Current.organization }
),
id: dom_id(conversation) do %>
<h4 class="is-size-4">
<%= conversation.listing.title %>
</h4>
<p class="has-text-right">
<%= local_date(conversation.created_at) %>
</p>
<% end %>
<% end %>

app/views/conversations/_form.html.erb
<%# locals: (message:, conversation:)  -%>

<%= form_with(model: message, url: conversation_messages_path(conversation),
class: "p-4", id: dom_id(conversation, :form)
) do |f| %>
<form-field class="field">
<%= f.text_area :body, class: "textarea has-fixed-size" %>
</form-field>
<layout-group class="buttons is-right mt-4">
<%= f.submit t(".send"), class: "button is-primary" %>
</layout-group>
<% end %>

app/views/conversations/index.html+mobile.erb
<%= content_for(:title) do %>
<%= t(".title") %>
<% end %>
<layout-columns class="columns">
    <layout-column class="column p-4" id="conversations">
        <%= render(@conversations) \
        || tag.h2(class: "has-text-centered is-size-3") do %>
        <%= t(".no_conversations") %>
        <% end %>
    </layout-column>
</layout-columns>

app/views/conversations/index.html.erb
<%= content_for(:title) do %>
<%= t(".title") %>
<% end %>
<layout-columns class="columns">
<layout-column
id="conversations"
class="column is-one-quarter p-4">
<%= render(@conversations) || tag.h2(class: "has-text-centered is-size-3") do %>
<%= t(".no_conversations") %>
<% end %>
</layout-column>
<%= turbo_frame_tag :conversation,
class: "column is-three-quarters" do %>
<br><br><br>
<h2 class="has-text-centered is-size-2">
<%= t(".no_selected_conversation") %>
</h2>
<% end %>
</layout-columns>

app/views/conversations/show.html.erb
<%= content_for(:title) do %>
<%= @conversation.listing.title %>
<% end %>
<%= turbo_frame_tag :conversation do %>
<div class="p-3">  
    <h1>vvvvvvvvvvvvvvvvvv<%= @pagy.last %></h1>

<%= render "messages/messages",
conversation: @conversation, messages: @conversation.messages.for_display.last_10,
pagy: @pagy %>
</div>
<%= render "form", message: @message, conversation: @conversation %> 
<%= turbo_stream.switch_class(dom_id(@conversation), "is-active") %>
<% end %>