config/routes.rb
require "sidekiq/web"
require "sidekiq/cron/web"

Rails.application.routes.draw do
  get 'feed/show'
  get 'users/new'
  get 'users/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "feed#show"
   
  get "sign_up", to: "users#new"

  post "sign_up", to: "users#create"

  get "login", to: "sessions#new"

  post "login", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  resource :profile, only: [:show, :update], controller: "users"

  resources :listings, except: :index do
    scope module: :listings do
      post :draft, to: "drafts#create", on: :collection
      patch :draft, to: "drafts#update"
      member do # both asr similar using member is expicit
        get :renew, to: "renew#show"
      end
      resource :contact, only: [:show], controller: "contact"
    end
    resource :saved_listings, only: [:create, :destroy], path: "save"
  end
  
  # only for cosmetic reeasons
  resource :saved_listings, only: :show

  resource :my_listings, only: :show

  namespace :users do
    patch "change_password", to: "passwords#update"
    resources :password_resets, only: [:new, :create, :update, :edit]
    resources :activation, only: [:show]
  end

  resource :search, only: :show, controller: "feed/searches"

  resource :search, only: :show, controller: "feed/searches" do
    get "tags/:tag", to: "feed/searches/tags#show", as: "tags"
  end


  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create, :index]
    get :unread_badge, to: "conversations/unread_badge#show", on: :collection
  end

  mount Sidekiq::Web => '/sidekiq'

end

# Draft Routes:

#     POST /listings/draft -> Listings::DraftsController#create
#     PATCH /listings/:id/draft -> Listings::DraftsController#update

# Saved Listings Routes:

#     POST /listings/:listing_id/save -> SavedListingsController#create
#     DELETE /listings/:listing_id/save -> SavedListingsController#destroy

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string
#  name            :string
#  password_digest :string
#  verified        :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord

  include Authentication, PasswordReset, Activation, PermittedAttributes

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP },
                    uniqueness: { case_sensitive: false }

  has_many :memberships, dependent: :destroy
  has_many :organizations, through: :memberships

  normalizes :name, with: ->(name) { name.strip }
  normalizes :email, with: ->(email) { email.strip.downcase }  

  before_validation :strip_extraneous_spaces

  has_one_attached :profile_photo

  has_and_belongs_to_many :saved_listings, join_table: "saved_listings", class_name: "Listing"

    # uses record id to generate signed string
  generates_token_for :authenticate, expires_in: 24.hours do
    password_salt.last(10)   #appends to the generated token. this is like jwt token 
  end
 
  private 

  def strip_extraneous_spaces
    self.name = self.name&.strip
    self.email = self.email&.strip
  end

end

app/models/user/activation.rb
module User::Activation
   extend ActiveSupport::Concern


   included do
     generates_token_for :activation
     after_create :send_activation_mail
   end


   def send_activation_mail
    token = generate_token_for :activation
    UserMailer.with(user: self).activation(token).deliver_now 
   end


end

app/models/user/authentication.rb
module User::Authentication

    extend ActiveSupport::Concern

    included do
      has_secure_password
      validates :password,
                on: [:create, :password_change],  # on save use this context save(context: password_change)
                presence: true, 
                length: { minimum: 8 }
      has_many :app_sessions
    end

    class_methods do
      def create_app_session(email:, password:)
          user = User.authenticate_by(email: email, password: password)
          user.app_sessions.create if user.present?
      end
    end  
    
    def authenticate_app_session(app_session_id, token)
      app_sessions.find(app_session_id).authenticate_token(token)
    rescue ActiveRecord::RecordNotFound
      nil  
    end

end    

app/models/user/password_reset.rb
module User::PasswordReset
  extend ActiveSupport::Concern

  included do
    # uses record id to generate signed string
    generates_token_for :password_reset, expires_in: 2.hours do
      password_salt.last(10)   #appends to the generated token. this is like jwt token 
    end
  end


  def reset_password
    app_sessions.destroy_all

    send_password_reset_email
  end


  private 

  def send_password_reset_email

    token = generate_token_for(:password_reset)
    
    UserMailer.with(user: self)
              .password_reset(token)
              .deliver_later
  end

end

app/models/user/permitted_attributes.rb
module User::PermittedAttributes
  extend ActiveSupport::Concern

  class_methods do
    def permitted_attributes
      [:name, :email, :password, :password_confirmation, :profile_photo]
    end

    def update_attributes
      [:name, :email, :profile_photo]
    end
  end

end

app/controllers/users/activation_controller.rb
class Users::ActivationController < ApplicationController
  skip_authentication

  def show

    @user = User.find_by_token_for(:activation, params[:id])

    if(@user.present?)
      message = t(".already_verified")
      verify_user && message = t(".success") unless @user.verified
      flash[:success] = message
      redirect_to root_path , status: :see_other
    else
      flash[:error] = t(".error")
      render "sessions/new" , status: :unprocessable_content
    end
    
  end


  private 

  def verify_user
    @user.verified = true
    @user.save
  end


end

app/controllers/users/password_resets_controller.rb
class Users::PasswordResetsController < ApplicationController
  skip_authentication

  before_action :load_user, only: [:edit, :update]

  def new
    
  end

  def edit
    
  end


  def update
    @user.assign_attributes(password_reset_params)

    if @user.save(context: :password_change)
      @app_session = @user.app_sessions.create
      log_in(@app_session)

      redirect_to root_path, status: :see_other, flash: { success: t(".success")}
    else 
      render :edit, status: :unprocessable_content  
    end
  end


  def create
    User.find_by(email: params[:email])&.reset_password
  end


  private 

  def load_user
    @user = User.find_by_token_for(:password_reset, params[:id])
    
    redirect_to new_users_password_reset_path,
      status: :see_other,
      flash: {
      error: t("users.password_resets.invalid_link")
    } unless @user.present?

  end

  def password_reset_params
    params.require(:user).permit(:password)
  end


end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < ApplicationController


  def update
    @user = Current.user
    @user.assign_attributes(password_params)

    if @user.save(context: :password_change)
      flash[:success] = t(".success")
      redirect_to profile_path, status: :see_other
    else
      render "users/show", status: :unprocessable_entity
    end
  end


  private 

     def password_params
       params.require(:user).permit(
         :password, 
         :password_challenge
         ).with_defaults(password_challenge: "")
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_authentication only: [:new, :create]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if(@user.save)
       @organization =  Organization.create(members: [@user])
       @app_session = @user.app_sessions.create
       log_in(@app_session)
       
       redirect_to root_path, status: :see_other, flash: { success: t(".welcome", name: @user.name)}
    else 
      render :new, status: :unprocessable_entity
    end
  end


  def show
    drop_breadcrumb t("application.navbar.profile")
    @user = Current.user
  end

  def update
    @user = Current.user
    # binding.b
    if(@user.update(update_params))
      flash[:success] = t(".success")
      redirect_to profile_path, status: :see_other
    else 
      render :edit, status: :unprocessable_entity
    end
  end

  private 

  def user_params
      params.require(:user).permit(User.permitted_attributes)
  end

  def update_params
      params.require(:user).permit(User.update_attributes)
  end


end

app/helpers/users/activation_helper.rb
module Users::ActivationHelper
end

app/helpers/users/password_resets_helper.rb
module Users::PasswordResetsHelper
end

app/helpers/users/passwords_helper.rb
module Users::PasswordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<% content_for :title, t(".title") %>

<layout-columns class="columns is-centered">
  <layout-column class="column box is-5 mt-6 p-5 m-4">
  <h1 class="title has-text-centered">
    <%= t(".title") %>
  </h1>
  <%= form_with(model: @user, url: sign_up_path, class: "is-flex is-flex-direction-column") do |form| %>
    <div class = "block">
        <%= form.label :name, class: "label" %>
        <%= form.text_field :name, class: "input" %>
    </div>
    <div class = "block">
        <%= form.label :email, class: "label" %>
        <%= form.text_field :email, class: "input" %>
    </div>
    <div class = "block">
        <%# <%= form.label :profile_photo, class: "label" %> %>
        <%# <%= form.file_field :profile_photo, class: "file-input", accept: "image/*" %> %>
    </div>
    <div class = "block">
        <%= form.label :password, class: "label" %>
        <%= form.password_field :password, class: "input" %>
    </div>
    <div class = "block">
        <%= form.label :password_confirmation, class: "label" %>
        <%= form.password_field :password_confirmation, class: "input" %>
    </div>
    <%= form.submit t(".sign_up"), class: "button is-primary is-large is-align-self-flex-end mb-3 mt-3"%>

    <% end %>
    </layout-column>
</layout-columns>

app/views/users/show.html.erb
<% content_for :title, Current.user.name %>


<%= turbo_frame_tag :user_details do %>
    <%= turbo_stream.update :current_user_name do %>
        <%= Current.user.name %>
    <% end %>
    <layout-columns class = "columns is-centered">
        <layout-column class ="column box is-5 mt-6 p-5 m-4">
            <h1 class="tiltle has-tex-centered">
                <%= t(".your_details")%>
            </h1>    

        <%= form_with(model: @user, url: profile_path, class: "is-flex is-flex-direction-column") do |form| %>
            <div class="block">
                <%= form.label :name, class: "label" %>
                <%= form.text_field :name, class: "input" %>
            </div>
            <div class="block">
                <%= form.label :email, class: "label" %>
                <%= form.email_field :email, class: "input" %>
            </div>
           <div class = "block">
              <%= form.label :profile_photo, class: "label" %>
              <%= form.file_field :profile_photo, class: "file-input", accept: "image/*" %>
           </div>
            <%= form.submit t(".save_profile"),class: "button is-primary is-align-self-flex-end mb-3 mt-3" %>
            <%= render "application/flashes" if turbo_frame_request? %>
        <% end %>  
    </layout-column>
  </layout-columns>
<% end %>

 <%= turbo_frame_tag :change_password do %>
    <layout-columns class="columns is-centered">
        <layout-column class="column box is-5 mt-6 p-5 m-4">
            <h1 class="title has-text-centered">
                <%= t(".change_password") %>
            </h1>
            <%= form_with(model: @user, url: users_change_password_path, class: "is-flex is-flex-direction-column") do |form| %>
                <div class="block">
                <%= form.label :password_challenge, value: t(".current_password"), class: "label" %>
                <%= form.password_field :password_challenge, class: "input" %>
                </div>
                <div class="block">
                <%= form.label :password, value: t(".new_password"), class: "label" %>
                <%= form.password_field :password, class: "input" %>
                </div>
                <%= form.submit t(".change_password_button"),class: "button is-primary is-align-self-flex-end mb-3 mt-3" %>
                <%= render "application/flashes" if turbo_frame_request? %>
            <% end %>
        </layout-column>
    </layout-columns>
<% end %>


 